services:
  # PostgreSQL Database for Billing Service
  postgres-billing:
    extends:
      file: compose.base.yaml
      service: postgres-billing

  # Redis for Billing Service
  redis-billing:
    extends:
      file: compose.base.yaml
      service: redis-billing

  # RabbitMQ for Billing Service
  rabbitmq-billing:
    extends:
      file: compose.base.yaml
      service: rabbitmq-billing

networks:
  billing-service-network:
    name: iqscaffold-billing-network-dev
    external: false


volumes:
  postgres_billing_data:
    name: iqscaffold_billing_postgres_data_dev
  redis_billing_data:
    name: iqscaffold_billing_redis_data_dev
  rabbitmq_billing_data:
    name: iqscaffold_billing_rabbitmq_data_dev
